const phones = [
  {
    id: '1',
    name: 'S-23 Ultra',
    company: 'Samsung',
    img: 'https://www.ephotozine.com/articles/samsung-galaxy-s23--samsung-galaxy-s23-----samsung-galaxy-s23-ultra-hands-on-review-36366/images/highres-P1010028_1675257673.jpg',
    price: '1299',
    desc: 'Now Ive had a chance to properly test the S23 Ultra over the last couple of weeks, I can sort of see why. Reviving legacy Galaxy Note-like features alongside a fresh list of exclusive goodies, the S23 Ultra is an entirely different proposition from its siblings. If you have enough money to splurge on a fancy new phone in 2023, then the S23 Ultra is probably the one to aspire to.',
  },
  {
    id: '2',
    name: 'Iphone 14 pro',
    company: 'Apple',
    img: 'https://s.hdnux.com/photos/01/27/46/17/22963193/5/rawImage.jpg',
    price: '1159',
    desc: 'At the end of the day, the iPhone 14 Pro is Apples best. And if youre considering getting one, now is still a good time to buy, but know that the rumored iPhone 15 series will likely come out in September. ',
  },
  {
    id: '3',
    name: 'Pixel 7 pro',
    company: 'Google',
    img: 'https://www.digitaltrends.com/wp-content/uploads/2022/10/google-pixel-7-pro-review-2.jpg?p=1',
    price: '999',
    desc: 'Thats where the Pixel 7 Pro is at its best, and I think it will remain that way even as we inevitably see an onslaught of new AI-driven features in the next Pixel phone this fall. If nothing else, Im hoping for a robot that will talk to the other robots for me. Thats gotta be on the way, right?',
  },
  {
    id: '4',
    name: 'One Plus 11',
    company: 'One-plus',
    img: 'https://amateurphotographer.com/wp-content/uploads/sites/7/2023/02/oneplus11_product_close-008.jpg',
    price: '899',
    desc: 'It is well made, feels nice and is narrower than its rivals, so is a little easier to hold despite being a big phone. The screen is great, the fingerprint scanner is responsive and the camera is solid if not class leading. The large circular camera lump on the back is divisive, however.',
  },
  {
    id: '5',
    name: 'Xperia 10V',
    company: 'Sony',
    img: 'https://amateurphotographer.com/wp-content/uploads/sites/7/2023/07/sony-xperia-10-v-black-in-hand-P7140005.jpg',
    price: '959',
    desc: 'Unfortunately, that about covers the list of new additions to the Xperia 10 V. Even though it is not that different from its predecessor, the Xperia 10 V remains a rather special device with a unique Sony "flavor" to it. We cant say whether that will be enough to guarantee its market success. What we can do, however, is delve into particulars and see what makes it tick.',
  },
  {
    id: '6',
    name: 'Edge',
    company: 'Razor',
    img: 'https://s.yimg.com/uu/api/res/1.2/bE3paiDPD3dUO8lVLqy3ww--~B/aD0xMjAwO3c9MjAwMDthcHBpZD15dGFjaHlvbg--/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2023-03/90385030-b9cc-11ed-bffd-d7be839716ff.cf.jpg',
    price: '1299',
    desc: 'The Razer Edge is an all-in-one Android-powered gaming package that includes a tablet equipped with a 6.8-inch OLED screen, Wi-Fi 6E connectivity, a Snapdragon G3x processor, and a Razer Kishi V2 Pro clip-on mobile game controller',
  },
];
export default phones